### ISSUE TITLE
`playbook_example2.yml` fails because of ubuntu

### ISSUE THREAD

**Issue by gpelouze** [DevOps-and-Cloud-based-Software/week4#8]
The `install nginx` task fails with error:

```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/t/tiff/libtiff5_4.3.0-6ubuntu0.3_amd64.deb  404  Not Found [IP: 54.165.17.230 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

This seems to to come from the Ubuntu archives, as the same playbook worked a few days ago.

**Comment by skoulouzis** [comment]
This looks like the VM is not able to connect to the outside world. 
Something to check is the security group's outbound rules.

**Comment by skoulouzis** [comment]
Also, some times installation is not working unless we run an update:
```yaml
    - name: update Debian
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: update RedHat
      ansible.builtin.yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'
```
I'll add this to the playbooks
